In [2]:
import numpy as np
import pandas as pd

In [3]:
#Exercise 1: 
#Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

arr1 = np.arange(1, 11).reshape(2, 5)
print(arr1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
#Exercise 2: 
#Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

arr2 = np.arange(1, 21)
extracted_elements = arr2[5:16]  # Extract elements from 5th to 15th index
print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15 16]


In [5]:
#Exercise 3:
#Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. 
#Then, add a new item to the series with the key 'pears' and the value 4.

data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)
series['pears'] = 4  # Adding a new item
print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [6]:
#Exercise 4:
#Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

data = {
    'name': ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Isaac", "Jack"],
    'age': [25, 30, 22, 35, 40, 28, 33, 26, 31, 29],
    'gender': ["Female", "Male", "Male", "Male", "Female", "Male", "Female", "Female", "Male", "Male"]
}
df = pd.DataFrame(data)
print(df)

      name  age  gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    David   35    Male
4      Eve   40  Female
5    Frank   28    Male
6    Grace   33  Female
7   Hannah   26  Female
8    Isaac   31    Male
9     Jack   29    Male


In [7]:
#Exercise 5:
#Add a new column to the data frame created in question 1, called occupation. 
#The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the datafram

df['occupation'] = ["Programmer", "Manager", "Analyst", "Programmer", "Manager", "Analyst", "Programmer", "Manager", "Analyst", "Programmer"]
print(df)


      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male  Programmer
4      Eve   40  Female     Manager
5    Frank   28    Male     Analyst
6    Grace   33  Female  Programmer
7   Hannah   26  Female     Manager
8    Isaac   31    Male     Analyst
9     Jack   29    Male  Programmer


In [8]:
#Exercise 6:
#Select the rows of the dataframe where the age is greater than or equal to 30.

filtered_df = df[df['age'] >= 30]
print(filtered_df)


    name  age  gender  occupation
1    Bob   30    Male     Manager
3  David   35    Male  Programmer
4    Eve   40  Female     Manager
6  Grace   33  Female  Programmer
8  Isaac   31    Male     Analyst


In [9]:
#Exercise 7:
#Convert this dataframe to a csv file and read that csv file, finally display the contents.  in python 

df.to_csv("data.csv", index=False)  # Save to CSV
read_df = pd.read_csv("data.csv")  # Read from CSV
print(read_df)



      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male  Programmer
4      Eve   40  Female     Manager
5    Frank   28    Male     Analyst
6    Grace   33  Female  Programmer
7   Hannah   26  Female     Manager
8    Isaac   31    Male     Analyst
9     Jack   29    Male  Programmer
